# Generated by Django 5.2 on 2025-04-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='createBy',
        ),
    ]
